include: package:flutter_lints/flutter.yaml

linter:
  rules:
    camel_case_types: true
    prefer_single_quotes: true
    avoid_catches_without_on_clauses: false

analyzer:
  exclude:
    - test/.test_coverage.dart