name: example

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_screwdriver:
    path: ../
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true