include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-raw-types: true
  exclude:
    - test/.test_coverage.dart

linter:
  rules:
    camel_case_types: true
    prefer_single_quotes: true
    avoid_catches_without_on_clauses: false
    omit_local_variable_types: true
    public_member_api_docs: true
    use_super_parameters: true