name: flutter_screwdriver
description: A flutter package aiming to provide useful extensions and helper functions to ease and speed up development.
version: 3.2.0
homepage: https://github.com/birjuvachhani/flutter_screwdriver

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  animations: ">=2.0.0 <3.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  analyzer: ^8.2.0
  intl: ^0.20.2
  mockito: ^5.5.1

scripts: scripts.yaml