name: flutter_screwdriver
description: A flutter package aiming to provide useful extensions and helper functions to ease and speed up development.
version: 1.0.0
homepage: https://github.com/birjuvachhani/flutter_screwdriver

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  animations: ^1.1.2

dev_dependencies:
  effective_dart: ^1.3.0
  flutter_test:
    sdk: flutter
