name: flutter_screwdriver
description: A flutter package aiming to provide useful extensions and helper functions to ease and speed up development.
version: 3.0.0
homepage: https://github.com/birjuvachhani/flutter_screwdriver

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  animations: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  analyzer: ^5.12.0
  intl: ^0.18.1

scripts: scripts.yaml