name: flutter_screwdriver
description: A flutter package aiming to provide useful extensions and helper functions to ease and speed up development.
version: 2.0.0
homepage: https://github.com/birjuvachhani/flutter_screwdriver

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter
  animations: ^2.0.3

dev_dependencies:
  effective_dart: ^1.3.2
  flutter_test:
    sdk: flutter
