name: Coverage

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  pull_request:
  workflow_dispatch:

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Flutter
        uses: subosito/flutter-action@v1
      - name: Install dependencies
        run: flutter packages get
      - name: Run tests
        run: flutter test --coverage
      - uses: codecov/codecov-action@v1
        with:
          file: coverage/lcov.info