name: Code Quality

on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'
  pull_request:
  workflow_dispatch:

jobs:
  quality:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Flutter
        uses: subosito/flutter-action@v1
      - name: Install dependencies
        run: flutter packages get
      - name: Analyzer
        run: flutter analyze
      - name: Dartfmt
        run: dartfmt --set-exit-if-changed -w --fix .
      - name: Dry Run
        run: flutter pub publish --dry-run
