name: Stats

on:
  push:
    paths:
      - '**.dart'
    branches:
      - main
    tags-ignore:
      - '**'
  workflow_dispatch:

jobs:
  update_stats:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Flutter
        uses: subosito/flutter-action@v2
      - name: Install dependencies
        run: flutter pub get
      - name: Generate Stats
        run: dart stats.dart
      - name: Update Stats on README.md
        uses: EndBug/add-and-commit@v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          add: 'README.md'
          message: Update Stats on README.md
          signoff: true